server:
  port: 8080
  servlet:
    context-path: /api
spring:
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:accounting;MODE=MySQL
    username: sa
    password: sa
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    object-factory: reengineering.ddd.mybatis.support.InjectableObjectFactory
logging:
  level:
    root: info


